# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  test212_jdk8:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: sbtcache
      - run: sbt ++2.12.10! core/test client/test realtime/test examples/compile
      - save_cache:
          key: sbtcache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test213_jdk11:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: sbtcache
      - run: sbt ++2.13.1! core/test client/test realtime/test examples/compile
      - save_cache:
          key: sbtcache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  release:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: sbtcache
      - run: echo "credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"$SONATYPE_USER\", \"$SONATYPE_PASSWORD\")" > ~/.sbt/1.0/sonatype.sbt
      - run: echo -n "${PGP_PUBLIC}" | base64 -d > /tmp/public.asc
      - run: echo -n "${PGP_SECRET}" | base64 -d > /tmp/secret.asc
      - run: sbt ++${SCALA_VERSION}! clean sonatypeBundleClean +publishSigned sonatypeBundleRelease

workflows:
  version: 2
  build:
    jobs:
      - test212_jdk8:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - test213_jdk11:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - release:
          context: Sonatype
          requires:
            - test212_jdk8
            - test213_jdk11
          filters:
            branches:
              only:
                - master
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
