name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '14', '17']
    name: Build project
    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
        cache: 'sbt'
    - name: Run tests
      run: sbt ++test
